
# For more information on configurations, see the services specification:
# https://docs.erisindustries.com/documentation/eris-cli/latest/services_specification/

# These fields marshal roughly into the [docker run] command, see:
# https://docs.docker.com/engine/reference/run/

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

name = "dualintegrator"
description = """
Dual integrator example application
"""

status = "alpha"

[service]
image = "dualintegrator:latest"
data_container = true
ports = ["3000:3000"]
environment = [
  "APP_PORT=3000",
  "IPFS_HOST=ipfs",
  "CHAIN_HOST=dualintegrator",
  "MY_HOST=localhost",
  "DOCUSIGN_USER=***",
  "DOCUSIGN_PASS=***",
  "DOCUSIGN_KEY=***"
]

[dependencies]
chains = ["dualintegrator"]
services = ["ipfs"]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"
